namespace Superprojekt

// Chart JS string-builders (data-attribute driven, rendered via
// Primitives.observedRender). Pure data, kept out of CardsPin's F# logic.
module CardCharts =

    // Vertical violin chart (data-ridge JSON): signed distance on y (0 = ref median), one column per mesh.
    // d.mini = compressed hover-probe variant (no badges/interaction). Full variant posts to .pc-ridge-bus
    // (Dom.OnInput): 'mv|d|alt|mesh' (cursor), 'click|mesh' (sticky toggle), 'clickout'. data-cursor
    // ({"d":…}, from 3D hover) moves the same cursor line without re-rendering.
    let ridgelineJs = [
        "  function placeholder(t){ var p = document.createElement('div'); p.className = 'pin-card-empty'; p.textContent = t; el.appendChild(p); }"
        "  if(!d.status || d.status === 'none'){ placeholder('No probe for this payload.'); return; }"
        "  if(d.status === 'running'){ placeholder('Probing…'); return; }"
        "  if(d.status === 'error'){ placeholder('Probe failed: ' + (d.reason || '')); return; }"
        "  var mini = !!d.mini;"
        "  var rows = d.rows || [];"
        "  var n = rows.length;"
        "  if(n === 0){ placeholder('No meshes.'); return; }"
        "  var accent = '#0891b2';"
        "  var SMALL_N = 20;"
        "  var w = mini ? 240 : Math.max(220, el.clientWidth || 296);"
        "  var axisW = mini ? 34 : 80;"
        "  var headerH = mini ? 16 : 24;"
        "  var badgeH = mini ? 10 : 16;"
        "  var H = mini ? 150 : 280;"
        "  var minCol = mini ? 24 : 40;"
        "  var colW = Math.max(minCol, (w - axisW) / n);"
        "  var svgW = Math.ceil(axisW + colW * n);"
        "  var y0 = d.ymin, y1 = d.ymax;"
        "  if(!(y1 > y0)){ y0 = -0.1; y1 = 0.1; }"
        "  var plotY0 = headerH, plotY1 = H - badgeH;"
        "  var ih = plotY1 - plotY0;"
        "  function sy(v){ return plotY0 + (y1 - v) / (y1 - y0) * ih; }"
        "  function fromY(py){ return y1 - (py - plotY0) / ih * (y1 - y0); }"
        "  var maxDen = 0;"
        "  rows.forEach(function(r){"
        "    (r.kde || []).forEach(function(p){ if(p[0] >= y0 && p[0] <= y1 && p[1] > maxDen) maxDen = p[1]; });"
        "    (r.kde2 || []).forEach(function(p){ if(p[0] >= y0 && p[0] <= y1 && p[1] > maxDen) maxDen = p[1]; });"
        "  });"
        "  function desat(hex){"
        "    var n = parseInt(hex.slice(1), 16);"
        "    var r0 = (n >> 16) & 255, g0 = (n >> 8) & 255, b0 = n & 255;"
        "    var m = (r0 + g0 + b0) / 3, f = 0.65;"
        "    return 'rgb(' + Math.round(r0 + (m - r0) * f) + ',' + Math.round(g0 + (m - g0) * f) + ',' + Math.round(b0 + (m - b0) * f) + ')';"
        "  }"
        "  var svg = document.createElementNS(ns,'svg');"
        "  svg.setAttribute('class','ridge-plot');"
        "  svg.setAttribute('width', svgW); svg.setAttribute('height', H);"
        "  svg.setAttribute('viewBox', '0 0 ' + svgW + ' ' + H);"
        "  function ln(xa,ya,xb,yb,stroke,sw,dash,op){"
        "    var l = document.createElementNS(ns,'line');"
        "    l.setAttribute('x1',xa); l.setAttribute('y1',ya); l.setAttribute('x2',xb); l.setAttribute('y2',yb);"
        "    l.setAttribute('stroke',stroke); l.setAttribute('stroke-width',sw);"
        "    if(dash) l.setAttribute('stroke-dasharray',dash);"
        "    if(op) l.setAttribute('stroke-opacity',op);"
        "    svg.appendChild(l); return l;"
        "  }"
        "  function txt(x,y,s,anchor,fill,size){"
        "    var t = document.createElementNS(ns,'text');"
        "    t.setAttribute('x',x); t.setAttribute('y',y);"
        "    t.setAttribute('text-anchor', anchor || 'middle');"
        "    t.setAttribute('font-family','SF Mono, Monaco, monospace');"
        "    t.setAttribute('font-size', size || '9');"
        "    t.setAttribute('fill', fill || '#475569');"
        "    t.textContent = s; svg.appendChild(t); return t;"
        "  }"
        "  var frame = document.createElementNS(ns,'rect');"
        "  frame.setAttribute('x', axisW); frame.setAttribute('y', plotY0);"
        "  frame.setAttribute('width', svgW - axisW); frame.setAttribute('height', ih);"
        "  frame.setAttribute('fill','#f8fafc'); frame.setAttribute('stroke','#cbd5e1'); frame.setAttribute('stroke-width','1');"
        "  svg.appendChild(frame);"
        "  var hoverRect = document.createElementNS(ns,'rect');"
        "  hoverRect.setAttribute('y', plotY0); hoverRect.setAttribute('height', ih);"
        "  hoverRect.setAttribute('fill', accent); hoverRect.setAttribute('fill-opacity','0.08');"
        "  hoverRect.style.display = 'none';"
        "  svg.appendChild(hoverRect);"
        "  var rawStep = (y1 - y0) / 4;"
        "  var pow = Math.pow(10, Math.floor(Math.log(rawStep) / Math.LN10));"
        "  var ms = rawStep / pow;"
        "  var step = (ms >= 5 ? 5 : ms >= 2 ? 2 : 1) * pow;"
        "  var dec = Math.max(0, -Math.floor(Math.log(step) / Math.LN10 + 1e-9));"
        "  for(var tv = Math.ceil(y0 / step) * step; tv <= y1 + step * 0.001; tv += step){"
        "    ln(axisW - 3, sy(tv), axisW, sy(tv), '#94a3b8', '1');"
        "    txt(axisW - 5, sy(tv) + 3, tv.toFixed(dec), 'end', '#475569', mini ? '8' : '9');"
        "  }"
        "  if(0 >= y0 && 0 <= y1) ln(axisW, sy(0), svgW, sy(0), '#64748b', '1', '3,3', '0.7');"
        "  if(!mini){"
        "    var at = txt(10, plotY0 + ih / 2, 'offset (m)', 'middle', '#64748b');"
        "    at.setAttribute('transform', 'rotate(-90 10 ' + (plotY0 + ih / 2) + ')');"
        "  }"
        "  rows.forEach(function(r, i){"
        "    var x0 = axisW + i * colW, cx = x0 + colW / 2;"
        "    var grey = r.count === 0;"
        "    if(mini){"
        "      var swm = document.createElementNS(ns,'rect');"
        "      swm.setAttribute('x', cx - 2.5); swm.setAttribute('y', 4);"
        "      swm.setAttribute('width', 5); swm.setAttribute('height', 5);"
        "      swm.setAttribute('fill', grey ? '#cbd5e1' : r.color);"
        "      svg.appendChild(swm);"
        "    } else {"
        "      var maxChars = Math.max(3, Math.floor((colW - 16) / 5.4));"
        "      var nm = r.name.length > maxChars ? r.name.slice(0, maxChars - 1) + '…' : r.name;"
        "      var sx0 = cx - (nm.length * 5.4 + 11) / 2;"
        "      var swr = document.createElementNS(ns,'rect');"
        "      swr.setAttribute('x', sx0); swr.setAttribute('y', 8);"
        "      swr.setAttribute('width', 7); swr.setAttribute('height', 7);"
        "      swr.setAttribute('fill', grey ? '#cbd5e1' : r.color);"
        "      svg.appendChild(swr);"
        "      txt(sx0 + 11, 15, nm, 'start', grey ? '#94a3b8' : '#0f172a');"
        "    }"
        "    if(!grey){"
        "      var refstd = d.refstd || 0;"
        "      var lod = 1.96 * Math.sqrt(refstd*refstd + (r.std||0)*(r.std||0));"
        "      if(lod > 0){ var bl=Math.max(y0,-lod), bh=Math.min(y1,lod); if(bh>bl){ var bnd=document.createElementNS(ns,'rect'); bnd.setAttribute('x',x0+1); bnd.setAttribute('y',sy(bh)); bnd.setAttribute('width',colW-2); bnd.setAttribute('height',Math.max(0,sy(bl)-sy(bh))); bnd.setAttribute('fill','#94a3b8'); bnd.setAttribute('fill-opacity','0.16'); svg.appendChild(bnd); } }"
        "      var hw = colW * 0.42;"
        "      var split = !!(r.kde2 && r.kde2.length > 1);"
        "      function halfArea(kdeRaw, sign, colour){"
        "        var kd = (kdeRaw || []).filter(function(p){ return p[0] >= y0 && p[0] <= y1; });"
        "        if(kd.length < 2 || maxDen <= 0) return;"
        "        var path = '';"
        "        kd.forEach(function(p, k){"
        "          path += (k === 0 ? 'M' : 'L') + (cx + sign * p[1] / maxDen * hw).toFixed(1) + ',' + sy(p[0]).toFixed(1);"
        "        });"
        "        path += 'L' + cx + ',' + sy(kd[kd.length - 1][0]).toFixed(1);"
        "        path += 'L' + cx + ',' + sy(kd[0][0]).toFixed(1) + 'Z';"
        "        var area = document.createElementNS(ns,'path');"
        "        area.setAttribute('d', path);"
        "        area.setAttribute('fill', colour); area.setAttribute('fill-opacity','0.4');"
        "        area.setAttribute('stroke', colour); area.setAttribute('stroke-width','1');"
        "        svg.appendChild(area);"
        "      }"
        "      if(split){"
        "        var dcol = desat(r.color);"
        "        halfArea(r.kde, -1, dcol);"
        "        halfArea(r.kde2, 1, r.color);"
        "        if(r.median >= y0 && r.median <= y1) ln(cx - colW * 0.3, sy(r.median), cx, sy(r.median), dcol, '1.5');"
        "        if(r.median2 >= y0 && r.median2 <= y1) ln(cx, sy(r.median2), cx + colW * 0.3, sy(r.median2), r.color, '1.5');"
        "        var qa1 = Math.max(r.q1, y0), qb1 = Math.min(r.q3, y1);"
        "        if(qb1 > qa1) ln(cx - 2, sy(qa1), cx - 2, sy(qb1), dcol, '2', null, '0.9');"
        "        var qa2 = Math.max(r.q12, y0), qb2 = Math.min(r.q32, y1);"
        "        if(qb2 > qa2) ln(cx + 2, sy(qa2), cx + 2, sy(qb2), r.color, '2', null, '0.9');"
        "        var ym1 = sy(Math.max(y0, Math.min(y1, r.median)));"
        "        var ym2 = sy(Math.max(y0, Math.min(y1, r.median2)));"
        "        if(Math.abs(ym2 - ym1) > 0.5){"
        "          ln(cx, ym1, cx, ym2, '#0f172a', '1');"
        "          var adir = ym2 > ym1 ? 1 : -1;"
        "          ln(cx, ym2, cx - 3, ym2 - adir * 4, '#0f172a', '1');"
        "          ln(cx, ym2, cx + 3, ym2 - adir * 4, '#0f172a', '1');"
        "        }"
        "        var dvv = r.median2 - r.median;"
        "        txt(cx + 5, (ym1 + ym2) / 2 + 3, 'Δ' + (dvv >= 0 ? '+' : '') + dvv.toFixed(3), 'start', '#0f172a', '8');"
        "      } else {"
        "        var kde = (r.kde || []).filter(function(p){ return p[0] >= y0 && p[0] <= y1; });"
        "        if(r.count > 0 && r.count < SMALL_N){"
        "          (r.samples || []).forEach(function(sv, si){"
        "            if(sv < y0 || sv > y1) return;"
        "            var jx = cx + (((si * 7) % 11) / 11 - 0.5) * hw * 1.1;"
        "            var dot = document.createElementNS(ns,'circle');"
        "            dot.setAttribute('cx', jx.toFixed(1)); dot.setAttribute('cy', sy(sv).toFixed(1));"
        "            dot.setAttribute('r','1.7'); dot.setAttribute('fill', r.color); dot.setAttribute('fill-opacity','0.75');"
        "            svg.appendChild(dot);"
        "          });"
        "        } else if(kde.length > 1 && maxDen > 0){"
        "          var path = '';"
        "          kde.forEach(function(p, k){"
        "            path += (k === 0 ? 'M' : 'L') + (cx + p[1] / maxDen * hw).toFixed(1) + ',' + sy(p[0]).toFixed(1);"
        "          });"
        "          for(var k = kde.length - 1; k >= 0; k--){"
        "            path += 'L' + (cx - kde[k][1] / maxDen * hw).toFixed(1) + ',' + sy(kde[k][0]).toFixed(1);"
        "          }"
        "          path += 'Z';"
        "          var area = document.createElementNS(ns,'path');"
        "          area.setAttribute('d', path);"
        "          area.setAttribute('fill', r.color); area.setAttribute('fill-opacity','0.4');"
        "          area.setAttribute('stroke', r.color); area.setAttribute('stroke-width','1');"
        "          svg.appendChild(area);"
        "        }"
        "        var sig = Math.abs(r.median) >= lod;"
        "        if(r.median >= y0 && r.median <= y1){"
        "          ln(cx - colW * 0.3, sy(r.median), cx + colW * 0.3, sy(r.median), sig ? r.color : '#94a3b8', sig ? '1.5' : '1', sig ? null : '2,2');"
        "          if(!sig) txt(cx + colW * 0.3 + 1, sy(r.median) + 3, 'n.s.', 'start', '#94a3b8', '7');"
        "        }"
        "        var qa = Math.max(r.q1, y0), qb = Math.min(r.q3, y1);"
        "        if(qb > qa) ln(cx, sy(qa), cx, sy(qb), r.color, '2.5', null, '0.9');"
        "      }"
        "    }"
        "    if(!mini) txt(cx, H - 4, grey ? '–' : ((r.far ? 'far · ' : '') + 'n=' + r.count), 'middle', grey ? '#94a3b8' : (r.far ? '#b45309' : '#475569'), '8');"
        "    if(!mini && d.sticky && d.sticky === r.id){"
        "      var st = document.createElementNS(ns,'rect');"
        "      st.setAttribute('x', x0 + 1.5); st.setAttribute('y', plotY0 + 1.5);"
        "      st.setAttribute('width', colW - 3); st.setAttribute('height', ih - 3);"
        "      st.setAttribute('fill','none'); st.setAttribute('stroke','#0f172a'); st.setAttribute('stroke-width','2');"
        "      svg.appendChild(st);"
        "    }"
        "  });"
        "  var cursor = ln(axisW, plotY0, svgW, plotY0, accent, '1.5');"
        "  cursor.style.display = 'none';"
        "  var cursorLabel = txt(svgW - 3, plotY0, '', 'end', accent, '8');"
        "  cursorLabel.style.display = 'none';"
        "  function setCursor(dv){"
        "    if(dv === null || dv < y0 || dv > y1){ cursor.style.display = 'none'; cursorLabel.style.display = 'none'; return; }"
        "    var y = sy(dv);"
        "    cursor.setAttribute('y1', y); cursor.setAttribute('y2', y);"
        "    cursor.style.display = '';"
        "    cursorLabel.setAttribute('y', y - 3);"
        "    cursorLabel.textContent = (dv >= 0 ? '+' : '') + dv.toFixed(2) + ' m';"
        "    cursorLabel.style.display = '';"
        "  }"
        "  el._hovering = false;"
        "  function applyCursorAttr(){"
        "    if(el._hovering) return;"
        "    var raw = el.getAttribute('data-cursor') || '{}';"
        "    var c; try { c = JSON.parse(raw); } catch(e) { return; }"
        "    setCursor(typeof c.d === 'number' ? c.d : null);"
        "  }"
        "  el._applyCursorAttr = applyCursorAttr;"
        "  if(!el._cursorObs){"
        "    el._cursorObs = new MutationObserver(function(){ if(el._applyCursorAttr) el._applyCursorAttr(); });"
        "    el._cursorObs.observe(el, {attributes:true, attributeFilter:['data-cursor']});"
        "  }"
        "  applyCursorAttr();"
        "  if(!mini){"
        "    var send = function(s){"
        "      var pr = el.closest('.pc-probe');"
        "      var b = pr ? pr.querySelector('.pc-ridge-bus') : null;"
        "      if(b){ b.value = s; b.dispatchEvent(new Event('input', {bubbles:true})); }"
        "    };"
        "    var lastSent = '', pend = null, raf = 0;"
        "    var flush = function(){ raf = 0; if(pend !== null && pend !== lastSent){ lastSent = pend; send(pend); } };"
        "    var queue = function(s){ pend = s; if(!raf) raf = requestAnimationFrame(flush); };"
        "    function colAt(x){ var i = Math.floor((x - axisW) / colW); return (i >= 0 && i < n) ? i : -1; }"
        // A3 range brush (3D map on only): drag a y-interval → highlight that surface band in 3D.
        "    var brushRect = document.createElementNS(ns,'rect');"
        "    brushRect.setAttribute('x', axisW); brushRect.setAttribute('width', svgW - axisW);"
        "    brushRect.setAttribute('fill', accent); brushRect.setAttribute('fill-opacity','0.16');"
        "    brushRect.setAttribute('stroke', accent); brushRect.setAttribute('stroke-opacity','0.6'); brushRect.setAttribute('stroke-width','1');"
        "    brushRect.style.display = 'none'; svg.appendChild(brushRect);"
        "    var brushing = false, brushY0 = 0, brushMoved = false;"
        "    svg.addEventListener('pointerdown', function(ev){"
        "      if(!d.brushon) return;"
        "      var rc = svg.getBoundingClientRect();"
        "      var x = ev.clientX - rc.left, y = ev.clientY - rc.top;"
        "      if(y >= plotY0 && y <= plotY1 && x >= axisW && !ev.altKey && !ev.shiftKey){"
        "        brushing = true; brushMoved = false; brushY0 = y;"
        "        try { svg.setPointerCapture(ev.pointerId); } catch(e) {}"
        "      }"
        "    });"
        "    svg.addEventListener('pointerenter', function(){ el._hovering = true; });"
        "    svg.addEventListener('pointermove', function(ev){"
        "      var rc = svg.getBoundingClientRect();"
        "      var x = ev.clientX - rc.left, y = ev.clientY - rc.top;"
        "      if(brushing){"
        "        var yy = Math.max(plotY0, Math.min(plotY1, y));"
        "        var lo = Math.min(brushY0, yy), hi = Math.max(brushY0, yy);"
        "        if(Math.abs(yy - brushY0) > 3) brushMoved = true;"
        "        brushRect.setAttribute('y', lo); brushRect.setAttribute('height', hi - lo); brushRect.style.display = '';"
        "        setCursor(null); hoverRect.style.display = 'none';"
        "        queue('brush|' + fromY(hi).toFixed(4) + '|' + fromY(lo).toFixed(4));"
        "        return;"
        "      }"
        "      el._hovering = true;"
        "      if(y < plotY0 || y > plotY1 || x < axisW){"
        "        setCursor(null); hoverRect.style.display = 'none'; queue('out'); return;"
        "      }"
        "      var dv = fromY(y);"
        "      var ci = colAt(x);"
        "      setCursor(dv);"
        "      if(ci >= 0){ hoverRect.setAttribute('x', axisW + ci * colW); hoverRect.setAttribute('width', colW); hoverRect.style.display = ''; }"
        "      else hoverRect.style.display = 'none';"
        "      queue('mv|' + dv.toFixed(4) + '|' + (ev.altKey ? '1' : '0') + '|' + (ci >= 0 ? rows[ci].id : ''));"
        "    });"
        "    svg.addEventListener('pointerup', function(ev){"
        "      if(brushing){"
        "        brushing = false;"
        "        try { svg.releasePointerCapture(ev.pointerId); } catch(e) {}"
        "        if(!brushMoved){ brushRect.style.display = 'none'; send('brushclear'); }"
        "      }"
        "    });"
        "    svg.addEventListener('pointerleave', function(){"
        "      el._hovering = false; hoverRect.style.display = 'none';"
        "      applyCursorAttr(); queue('out');"
        "    });"
        "    svg.addEventListener('click', function(ev){"
        "      if(brushMoved){ brushMoved = false; return; }"
        "      var rc = svg.getBoundingClientRect();"
        "      var x = ev.clientX - rc.left, y = ev.clientY - rc.top;"
        "      var ci = colAt(x);"
        "      if(y >= plotY0 && y <= plotY1 && ci >= 0){"
        "        lastSent = '';"
        "        if(ev.altKey) send('lock|' + fromY(y).toFixed(4));"
        "        else if(ev.shiftKey) send('apick|' + fromY(y).toFixed(4) + '|' + rows[ci].id);"
        "        else send('click|' + rows[ci].id);"
        "      }"
        "    });"
        "    if(!el._docClick){"
        "      el._docClick = function(ev){"
        "        if(!document.contains(el)){ document.removeEventListener('click', el._docClick); el._docClick = null; return; }"
        // Clear sticky only on clicks outside the whole .pc-probe section, so its header controls (3D map, slice) don't wipe the soloed column.
        "        var box = el.closest('.pc-probe') || el;"
        "        if(!box.contains(ev.target)) send('clickout');"
        "      };"
        "      document.addEventListener('click', el._docClick);"
        "    }"
        "  }"
        "  el.appendChild(svg);"
    ]

    // Three-source stacked bar for a data-srcs = [d,a,c] attribute.
    let probeBarJs = [
        "  if(!d || d.length < 3) return;"
        "  var labels = ['Dataset error (sensor / reconstruction)','Algorithm residual (registration, correlated across the mesh)','Local conditioning (geometric observability of the marker)'];"
        "  var colours = ['#60a5fa','#f59e0b','#a78bfa'];"
        "  var total = d[0] + d[1] + d[2];"
        "  if(total <= 0) return;"
        "  d.forEach(function(v, i){"
        "    var s = document.createElement('div');"
        "    s.style.width = (v / total * 100) + '%';"
        "    s.style.background = colours[i];"
        "    s.style.height = '100%';"
        "    s.title = labels[i] + ': ' + v.toFixed(4) + ' m';"
        "    el.appendChild(s);"
        "  });"
    ]
