// index.js
const puppeteer = require('puppeteer');

(async () => {
  // Launch a browser
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();

  // Go to a webpage
  await page.goto('http://localhost:5432/?nocache=true', { waitUntil: 'load' });
  await page.waitForSelector('#loader', { hidden: true });
  await page.waitForFunction(() => document.querySelector('#loading-done') !== null); 
  await new Promise(resolve => setTimeout(resolve, 1000)); // wait a bit more to ensure all shaders are compiled
    
  // Run JavaScript in the page context
  const result = await page.evaluate(() => {
    let text = "namespace Superprojekt\n";
    
    text += "// ========== Shader Cache =============\n";
    text += "// This file is auto-generated by precompile.js. DO NOT CHANGE\n";
    
    text += "module ShaderCache =\n";
    text += "    let cacheContent =\n        [|\n"
    for(let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        let value = localStorage.getItem(key)
        if(key.startsWith("super_cache")) continue;
        text += "            \"" + key + "\", \"" + value + "\"\n";
    }
    text += "        |]";
    return text;
  });

  console.log(result);

  await browser.close();
})();